---
title: Akshay Deo
timezone: UTC
collections:
  em_posts:
    title: EM
    output: true
    sidebar_label: EM
  posts:
    title: Posts
    output: true
    sidebar_label: Posts
  products:
    title: Products
    output: true
    sidebar_label: Products
  uploads:
    title: Uploads
    output: true
    sidebar_label: Uploads
  weblog:
    title: Weblog
    output: true
    sidebar_label: Weblog
feed:
  collections:
    em_posts:
      title: Engineering Management Blog
      description: Open source implementation of engineering management processes
        for happy, healthy and productive teams!
      path: "/em.xml"
      tags:
      - engineering management
      - technology
future: true
permalink: "/blog/:year/:month/:day/:title/"
tagline: Product Development from Engineering Perspective
description: "\U0001F44B I am Akshay Deo, a computer engineering from Pune. Co-founded
  3 Startups, built 20+ Products and currently working on Postman as Head of Product
  Engineering."
url: https://www.akshaydeo.com
tag_dir: tag
tag_page_layout: tag_index
tag_page_dir: tag
twitter:
  username: akshay_deo
  card: summary
social:
  name: Aksahy Deo
  links:
  - https://twitter.com/akshay_deo
  - https://www.linkedin.com/in/akshaymdeo/
  - https://github.com/akshaydeo
author:
  name: Akshay Deo
  url: https://twitter.com/akshay_deo
  twitter: akshay_deo
  card: summary
paginate: 10
paginate_path: writing/page:num
disqus_short_name: akshaydeo
disqus_show_comment_count: true
version: 2.1.0
github:
  repo: https://github.com/akshaydeo/blog
google_analytics_tracking_id: UA-56560447-1
plugins_dir: "./_plugins"
plugins:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-gist
- liquid_reading_time
- liquid_pluralize
- jekyll-sitemap
- github-pages
- jekyll-feed
jekyll_admin:
  hidden_links:
  - datafiles
  homepage: pages
