# Permalinks
permalink: /blog/:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:            'Akshay Deo'
tagline:          'Product Development from Engineering Perspective'
description:      '👋 I am Akshay Deo, a computer engineering from Pune. Co-founded 3 Startups, built 20+ Products and currently working with Slack.'
url:              https://www.akshaydeo.com
baseurl:          /

twitter:
  username: akshay_deo
  card: summary

social:
  name: Aksahy Deo
  links:
    - https://twitter.com/akshay_deo
    - https://www.linkedin.com/in/akshaymdeo/
    - https://github.com/akshaydeo

author:
  name:           'Akshay Deo'
  url:            https://twitter.com/akshay_deo
  twitter:        akshay_deo
  card: summary

paginate:         10
paginate_path:    writing/page:num


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/akshaydeo

# Disqus
disqus_short_name: rashcoder
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-56560447-1

plugins_dir:
  - jekyll-seo-tag