# Permalinks
permalink: /blog/:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:            amd
tagline:          'code for life'
description:      ''
url:              http://akshaydeo.com
baseurl:          /

author:
  name:           'Akshay Deo'
  url:            https://twitter.com/akshay_deo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/akshaydeo

# Disqus
disqus_short_name: rashcoder
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-56560447-1

# gems
gems:
  - jemoji
