---
title: Akshay Deo
timezone: UTC
collections:
  em_posts:
    title: EM
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
feed:
  collections:
    em_posts:
      title: Engineering Management Blog
      description: Open source implementation of engineering management processes
        for happy, healthy and productive teams!
      path: "/em.xml"
      categories:
      - engineering management
      - technology
permalink: "/blog/:year/:month/:day/:title/"
tagline: Product Development from Engineering Perspective
description: "\U0001F44B I am Akshay Deo, a computer engineering from Pune. Co-founded
  3 Startups, built 20+ Products and currently working with Slack."
url: https://www.akshaydeo.com
twitter:
  username: akshay_deo
  card: summary
social:
  name: Aksahy Deo
  links:
  - https://twitter.com/akshay_deo
  - https://www.linkedin.com/in/akshaymdeo/
  - https://github.com/akshaydeo
author:
  name: Akshay Deo
  url: https://twitter.com/akshay_deo
  twitter: akshay_deo
  card: summary
paginate: 10
paginate_path: writing/page:num
disqus_short_name: akshaydeo
disqus_show_comment_count: false
version: 2.1.0
github:
  repo: https://github.com/akshaydeo
google_analytics_tracking_id: UA-56560447-1
plugins_dir: "./_plugins"
plugins:
- jekyll-seo-tag
- jekyll-paginate
- jekyll-gist
- liquid_reading_time
- liquid_pluralize
- jekyll-sitemap
- github-pages
- jekyll-feed
