# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            amd
tagline:          'code for life'
description:      'Tech Lead @ media.net.<br>Creator of AppSurfer<br>Ex Co-Founder of RainingCloud, Betacraft <a href="https://twitter.com/akshay_deo" target="_blank">@akshay_deo</a>.'
url:              http://akshaydeo.com
baseurl:          /

author:
  name:           'Akshay Deo'
  url:            https://twitter.com/akshay_deo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/akshaydeo

gems: [jekyll-paginate, jekyll-gist, octopress-image-tag]
